# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs = -Xmx1G
org.gradle.daemon = true
org.gradle.parallel = true
org.gradle.caching = true
org.gradle.configuration-cache = true

parchment_minecraft_version = 1.21.1
parchment_mappings_version = 2024.11.17

minecraft_version = 1.21.1
minecraft_version_range = [1.21.1]
neo_version = 21.1.214
loader_version_range = [1,)

mod_id = createcafe
mod_name = Create Cafe
mod_license = GLP 2.0
mod_version = 1.4.1
mod_group_id = com.Imphuls3.createcafe
mod_authors = Myst (1mphuls3)
mod_description = Example mod description.\nNewline characters can be used and will be replaced properly.

create_version = 6.0.8-169
flywheel_version = 1.0.5
ponder_version = 1.0.66

registrate_version = MC1.21-1.3.0+67

jei_version = 19.25.1.328